export const TODO_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  OVERDUE: 'OVERDUE',
  COMPLETED_SUCCESS: 'COMPLETED_SUCCESS',
  COMPLETED_FAILURE: 'COMPLETED_FAILURE',
} as const;

export type TodoStatus = (typeof TODO_STATUS)[keyof typeof TODO_STATUS];
